baseURL: http://aflynn.uk
title: Alastair Flynn
defaultContentLanguage: 'en'
googleAnalytics: ''

params:
  image: '/images/banner.png'
  #copyright: All rights reserved.
  author: Alastair Flynn
  logo: 'camerame.jpg'
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        # art: 4
        # archive: 6
        graphic: 3
        web: 2
        ny: 1
        default: 3
      mobile:
        default: 2
        # archive: 3
  socials:
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:af@aflynn.uk'
    - icon: 'fab fa-github fa-lg'
      url: 'https://github.com/Aflynn50/'
    - icon: 'fab fa-linkedin-in fa-lg'
      url: 'https://linkedin.com/in/alastair-flynn-6922a8191'
  homepage: "/about" # homepage link, mostly same with menu.main[0]
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: about
      url: /about/
      weight: 1
    - name: blog
      url: /blog/
      weight: 3
    - name: new york
      url: /tags/ny
      weight: 5
    - name: cv
      url: https://www.dropbox.com/
      weight: 5
   
